// Keyboard layout mappings
export const LAYOUTS = {
  QWERTY: 'QWERTY',
  AZERTY: 'AZERTY'
};

// Bidirectional mapping for each layout
export const KEY_MAPPING = {
  'QWERTY': {
    // Letters (English to Arabic)
    'q': 'ض',
    'w': 'ص',
    'e': 'ث',
    'r': 'ق',
    't': 'ف',
    'y': 'غ',
    'u': 'ع',
    'i': 'ه',
    'o': 'خ',
    'p': 'ح',
    '[': 'ج',
    ']': 'د',
    'a': 'ش',
    's': 'س',
    'd': 'ي',
    'f': 'ب',
    'g': 'ل',
    'h': 'ا',
    'j': 'ت',
    'k': 'ن',
    'l': 'م',
    ';': 'ك',
    "'": 'ط',
    '\\':'\\',
    '`': '٫',
    'z': 'ئ',
    'x': 'ء',
    'c': 'ؤ',
    'v': 'ر',
    'b': 'لا',
    'n': 'ى',
    'm': 'ة',
    ',': 'و',
    '.': 'ز',
    '/': 'ظ',
    
    // Numbers (English to Arabic)
    '§': 'ذ',
    '1': '١',
    '2': '٢',
    '3': '٣',
    '4': "٤",
    '5': '٥',
    '6': '٦',
    '7': '٧',
    '8': '٨',
    '9': '٩',
    '0': '٠',
    '-': '-',
    
    // Arabic to English (reverse mapping)
    'ض': 'q',
    'ص': 'w',
    'ث': 'e',
    'ق': 'r',
    'ف': 't',
    'غ': 'y',
    'ع': 'u',
    'ه': 'i',
    'خ': 'o',
    'ح': 'p',
    'ج': '[',
    'د': ']',
    'ش': 'a',
    'س': 's',
    'ي': 'd',
    'ب': 'f',
    'ل': 'g',
    'ا': 'h',
    'ت': 'j',
    'ن': 'k',
    'م': 'l',
    'ك': ';',
    'ط': "'",
    '\\': '\\',
    '٫': '`',
    'ئ': 'z',
    'ء': 'x',
    'ؤ': 'c',
    'ر': 'v',
    'لا': 'b',
    'ى': 'n',
    'ة': 'm',
    'و': ',',
    'ز': '.',
    'ظ': '/',
    
    // Arabic numbers to English
    'ذ': '§',
    '١': '1',
    '٢': '2',
    '٣': '3',
    '٤': '4',
    '٥': '5',
    '٦': '6',
    '٧': '7',
    '٨': '8',
    '٩': '9',
    '٠': '0',
    '-': '-'
  },

  'AZERTY': {
    // Letters (English to Arabic)
    'a': 'ض',
    'z': 'ص',
    'e': 'ث',
    'r': 'ق',
    't': 'ف',
    'y': 'غ',
    'u': 'ع',
    'i': 'ه',
    'o': 'خ',
    'p': 'ح',
    '^': 'ج',
    '$': 'د',
    'q': 'ش',
    's': 'س',
    'd': 'ي',
    'f': 'ب',
    'g': 'ل',
    'h': 'ا',
    'j': 'ت',
    'k': 'ن',
    'l': 'م',
    'm': 'ك',
    "ù": 'ط',
    '`':'ذ',
    '<': '\\',
    'w': 'ئ',
    'x': 'ء',
    'c': 'ؤ',
    'v': 'ر',
    'b': 'لا',
    'n': 'ى',
    ',': 'ة',
    ';': 'و',
    ':': 'ز',
    '=': 'ظ',
    
    // Numbers (English to Arabic)
    '@': '>',
    '&': '&',
    'é': 'é',
    '"': '"',
    "'": "'",
    '(': ')',
    '-': '-',
    'è': 'è',
    '!': '_',
    'ç': 'ç',
    'à': 'à',
    ')': '(',
    
    // Arabic to English (reverse mapping)
    'ض': 'a',
    'ص': 'z',
    'ث': 'e',
    'ق': 'r',
    'ف': 't',
    'غ': 'y',
    'ع': 'u',
    'ه': 'i',
    'خ': 'o',
    'ح': 'p',
    'ج': '^',
    'د': '$',
    'ش': 'q',
    'س': 's',
    'ي': 'd',
    'ب': 'f',
    'ل': 'g',
    'ا': 'h',
    'ت': 'j',
    'ن': 'k',
    'م': 'l',
    'ك': 'm',
    'ط': 'ù',
    'ذ': '`',
    '\\': '<',
    'ئ': 'w',
    'ء': 'x',
    'ؤ': 'c',
    'ر': 'v',
    'لا': 'b',
    'ى': 'n',
    'ة': ',',
    'و': ';',
    'ز': ':',
    'ظ': '=',
    
    // Arabic numbers to English
    '>': '@',
    '&': '&',
    'é': 'é',
    '"': '"',
    "'": "'",
    ')': '(',
    '-': '§',
    'è': 'è',
    '_': '!',
    'ç': 'ç',
    'à': 'à',
    '(': ')'
  }
};


// Get equivalent key based on current layout
export function getEquivalentKey(key, currentLayout) {  
  key = key.toLowerCase();
  const mapping = KEY_MAPPING[currentLayout];
  
  if (!mapping) {
    console.log('[Constants] No mapping found for layout:', currentLayout);
    return key;
  }
  
  const equivalentKey = mapping[key];
  console.log('[Constants] Found equivalent:', equivalentKey || key);
  
  return equivalentKey || key;
}